(function(){
  gameLoop = new LNXAstAttack.GameLoop();
  PIXI.loader
   .add("./img/welcome_screen_2.jpg")
   .add("./img/youlose_screen.png")
   .add("./img/youwon_screen.png")
   .add("./img/spaceship.pod.1.small.red.png")
   .add("./img/spaceship.pod.1.small.blue.png")
   .add("./img/spaceship.pod.1.small.yellow.png")
   .add("./img/spinner.png")
   .add("./img/spinnerl2.png")
   .add("./img/red_ball.png")
   .add("./img/cyan_ball.png")
   .add("./img/cyan_radial.png")
   .add("./img/asteroid_sprite.png")
   .add("./img/asteroid_invencible.png")
   .add("./img/asteroid_death.png")
   .add("./img/space.jpg")
   .add("./img/earth-light.png")
   .add("./img/earth-fading.png")
   .add("./img/explosion/boom3.png")
   .add("./img/explosion/explosion_01_strip13_small.png")
   .add("./img/explosion/explosion_01_strip13_medium.png")
   .load(gameLoop.start);
}());
